commonroad-v1:
  verbose: 2
  tensorboard_log: "./logs_tensorboard/"
  n_steps: 147
  batch_size: 2352
  gae_lambda: 0.99
  gamma: 0.97
  n_epochs: 5
  ent_coef: 0.01
  learning_rate: !!float 3.0e-4
  clip_range: 0.1
